### ISSUE TITLE
Gaussian Attack problem

### ISSUE THREAD

**Issue by zhongjian-zhang** [yflyl613/FedRec#1]
When i use Gaussian Attack to generate Norm distribution in ml-1m dataset, there is a error.

`ValueError: Expected parameter scale (Tensor of shape (237184,)) of distribution Normal(loc: torch.Size([237184]), scale: torch.Size([237184])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([9.5281e-05, 4.3245e-05, 9.2144e-05,  ..., 1.0458e-05, 5.7352e-06,
        3.1931e-05], device='cuda:0')`

**Comment by yflyl613** [comment]
> When i use Gaussian Attack to generate Norm distribution in ml-1m dataset, there is a error.
> 
> `ValueError: Expected parameter scale (Tensor of shape (237184,)) of distribution Normal(loc: torch.Size([237184]), scale: torch.Size([237184])) to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values: tensor([9.5281e-05, 4.3245e-05, 9.2144e-05, ..., 1.0458e-05, 5.7352e-06, 3.1931e-05], device='cuda:0')`

I also encountered this error during my experiments. Finally, I found that `torch.distributions.normal.Normal` behaves differently with different versions of PyTorch. You may also try PyTorch 1.7.1 and it should be ok.
