### ISSUE TITLE
A question about Fang Attack

### ISSUE THREAD

**Issue by zhongjian-zhang** [yflyl613/FedRec#2]
![image](https://user-images.githubusercontent.com/59616556/212237021-ac4dc0e7-d8ea-4ca5-b364-f9232677950f.png)
![image](https://user-images.githubusercontent.com/59616556/212237044-4d37f703-b4d0-4749-963f-9000f4843b05.png)
Hi， Are you sure the sign is ”+“ when generate  the client_item_grad  in update function？I think the sign should be "-", because the sign generated by the benign item_grad_mean, so the sign direction shouble be derection of gradient optimized,  But attacker adds noise in opposite directions to the average normal gradient in the Fang Attack.

**Comment by yflyl613** [comment]
> ![image](https://user-images.githubusercontent.com/59616556/212237021-ac4dc0e7-d8ea-4ca5-b364-f9232677950f.png) ![image](https://user-images.githubusercontent.com/59616556/212237044-4d37f703-b4d0-4749-963f-9000f4843b05.png) Hi， Are you sure the sign is ”+“ when generate the client_item_grad in update function？I think the sign should be "-", because the sign generated by the benign item_grad_mean, so the sign direction shouble be derection of gradient optimized, But attacker adds noise in opposite directions to the average normal gradient in the Fang Attack.

In Fang Attack, the attacker adds noise opposite to the direction of how the model parameter changes, which is opposite to the sign of the gradient (the model parameter is updated as $w'=w-\lambda \nabla g$). So I think it should be '+'.
